export const indexSql = `
CREATE INDEX IF NOT EXISTS "idx_task_workspace" ON "Task"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_task_workspace_updated" ON "Task"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_task_workspace_status" ON "Task"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_task_workspace_project" ON "Task"("workspaceId", "project");
CREATE INDEX IF NOT EXISTS "idx_task_workspace_sprint" ON "Task"("workspaceId", "sprintId");
CREATE INDEX IF NOT EXISTS "idx_task_project_active_updated" ON "Task"("project", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_task_workspace_active_updated" ON "Task"("workspaceId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_task_workspace_active_status_updated" ON "Task"("workspaceId", "status", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_task_status" ON "Task"("status");
CREATE INDEX IF NOT EXISTS "idx_task_assignee" ON "Task"("assignee");
CREATE INDEX IF NOT EXISTS "idx_bug_workspace" ON "Bug"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_updated" ON "Bug"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_status" ON "Bug"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_project" ON "Bug"("workspaceId", "project");
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_module" ON "Bug"("workspaceId", "module");
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_sprint" ON "Bug"("workspaceId", "sprintId");
CREATE INDEX IF NOT EXISTS "idx_bug_project_active_created" ON "Bug"("project", "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_active_updated" ON "Bug"("workspaceId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_active_created" ON "Bug"("workspaceId", "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_workspace_active_status_updated" ON "Bug"("workspaceId", "status", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_bug_status" ON "Bug"("status");
CREATE INDEX IF NOT EXISTS "idx_bug_suggesteddev" ON "Bug"("suggestedDev");
CREATE INDEX IF NOT EXISTS "idx_testcase_workspace" ON "TestCase"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_testcase_workspace_updated" ON "TestCase"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_testcase_workspace_status" ON "TestCase"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_testcase_workspace_suite" ON "TestCase"("workspaceId", "testSuiteId");
CREATE INDEX IF NOT EXISTS "idx_testcase_workspace_active_suite" ON "TestCase"("workspaceId", "testSuiteId", "id") WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testcase_assignee" ON "TestCase"("assignee");
CREATE INDEX IF NOT EXISTS "idx_testcase_status" ON "TestCase"("status");
CREATE INDEX IF NOT EXISTS "idx_testcase_suite" ON "TestCase"("testSuiteId");
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace" ON "TestPlan"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_updated" ON "TestPlan"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_project" ON "TestPlan"("workspaceId", "project");
CREATE INDEX IF NOT EXISTS "idx_testplan_project_active_updated" ON "TestPlan"("project", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_sprint" ON "TestPlan"("workspaceId", "sprint");
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_status" ON "TestPlan"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_endDate" ON "TestPlan"("workspaceId", "endDate");
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_token" ON "TestPlan"("workspaceId", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_active_updated" ON "TestPlan"("workspaceId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testplan_workspace_active_sprint" ON "TestPlan"("workspaceId", "sprint", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testsuite_workspace" ON "TestSuite"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_testsuite_workspace_updated" ON "TestSuite"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_testsuite_workspace_plan" ON "TestSuite"("workspaceId", "testPlanId");
CREATE INDEX IF NOT EXISTS "idx_testsuite_workspace_status" ON "TestSuite"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_testsuite_assignee" ON "TestSuite"("assignee");
CREATE INDEX IF NOT EXISTS "idx_testsuite_workspace_token" ON "TestSuite"("workspaceId", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_testsuite_plan_active_updated" ON "TestSuite"("testPlanId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testsuite_workspace_active_plan_updated" ON "TestSuite"("workspaceId", "testPlanId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_activitylog_workspace" ON "ActivityLog"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_activitylog_workspace_created" ON "ActivityLog"("workspaceId", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_searchtoken_unique" ON "SearchToken"("company", "entityType", "entityId", "token");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_searchtoken_lookup" ON "SearchToken"("company", "entityType", "entityIdInt", "token");
CREATE INDEX IF NOT EXISTS "idx_searchtoken_workspace_token" ON "SearchToken"("workspaceId", "entityType", "token");
CREATE INDEX IF NOT EXISTS "idx_sprint_workspace" ON "Sprint"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_sprint_workspace_updated" ON "Sprint"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_sprint_workspace_name" ON "Sprint"("workspaceId", "name");
CREATE INDEX IF NOT EXISTS "idx_sprint_workspace_status" ON "Sprint"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_sprint_workspace_start" ON "Sprint"("workspaceId", "startDate");
CREATE INDEX IF NOT EXISTS "idx_sprint_workspace_endDate" ON "Sprint"("workspaceId", "endDate");
CREATE INDEX IF NOT EXISTS "idx_sprint_name_active_start" ON "Sprint"("name", "startDate" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_sprint_workspace_active_start" ON "Sprint"("workspaceId", "startDate" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testcase_workspace_token" ON "TestCase"("workspaceId", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_testsession_workspace_scope_date" ON "TestSession"("workspaceId", "scope", "date");
CREATE INDEX IF NOT EXISTS "idx_testsession_scope_active_date" ON "TestSession"("scope", "date" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_testsession_workspace_active_scope_date" ON "TestSession"("workspaceId", "scope", "date" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_meetingnote_workspace_updated" ON "MeetingNote"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_workspace_date" ON "MeetingNote"("workspaceId", "date");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_workspace_token" ON "MeetingNote"("workspaceId", "publicToken");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_workspace_project" ON "MeetingNote"("workspaceId", "project");
CREATE INDEX IF NOT EXISTS "idx_meetingnote_project_active_date" ON "MeetingNote"("project", "date" DESC, "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_meetingnote_workspace_active_date" ON "MeetingNote"("workspaceId", "date" DESC, "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_invite_workspace" ON "Invite"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_invite_token" ON "Invite"("token");
CREATE INDEX IF NOT EXISTS "idx_invite_company_status" ON "Invite"("company", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_workspace_name" ON "Workspace"("name");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_workspace_slug" ON "Workspace"("slug");
CREATE INDEX IF NOT EXISTS "idx_workspace_createdby" ON "Workspace"("createdByUserId");
CREATE INDEX IF NOT EXISTS "idx_workspacemember_workspace" ON "WorkspaceMembership"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_workspacemember_user" ON "WorkspaceMembership"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_workspacemember_unique" ON "WorkspaceMembership"("workspaceId", "userId");
CREATE INDEX IF NOT EXISTS "idx_user_workspace_active_created" ON "User"("workspaceId", "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "idx_apikey_keyhash" ON "ApiKey"("keyHash");
CREATE INDEX IF NOT EXISTS "idx_apikey_user_created" ON "ApiKey"("userId", "createdAt" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_assignee_userId" ON "Assignee"("userId") WHERE "userId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_assignee_workspace_updated" ON "Assignee"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_assignee_workspace_name" ON "Assignee"("workspaceId", "name");
CREATE INDEX IF NOT EXISTS "idx_assignee_workspace_status" ON "Assignee"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_assignee_workspace_active_updated" ON "Assignee"("workspaceId", "updatedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_deployment_workspace_updated" ON "Deployment"("workspaceId", "updatedAt");
CREATE INDEX IF NOT EXISTS "idx_deployment_workspace_project" ON "Deployment"("workspaceId", "project");
CREATE INDEX IF NOT EXISTS "idx_deployment_project_active_date" ON "Deployment"("project", "date" DESC, "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_deployment_workspace_status" ON "Deployment"("workspaceId", "status");
CREATE INDEX IF NOT EXISTS "idx_deployment_workspace_date" ON "Deployment"("workspaceId", "date");
CREATE INDEX IF NOT EXISTS "idx_deployment_workspace_active_date" ON "Deployment"("workspaceId", "date" DESC, "createdAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_execrun_company_suite" ON "ExecutionRun"("company", "testSuiteId");
CREATE INDEX IF NOT EXISTS "idx_execrun_company_status" ON "ExecutionRun"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_execrun_suite_number" ON "ExecutionRun"("testSuiteId", "runNumber" DESC);
CREATE INDEX IF NOT EXISTS "idx_execrun_company_active" ON "ExecutionRun"("company", "startedAt" DESC) WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_caseverdict_run" ON "CaseVerdict"("executionRunId");
CREATE INDEX IF NOT EXISTS "idx_caseverdict_company_run" ON "CaseVerdict"("company", "executionRunId");
CREATE INDEX IF NOT EXISTS "idx_caseverdict_testcase" ON "CaseVerdict"("testCaseId");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_caseverdict_run_case" ON "CaseVerdict"("executionRunId", "testCaseId");
CREATE INDEX IF NOT EXISTS "idx_dashcomment_workspace_entity" ON "DashboardComment"("workspaceId", "entityType", "entityId");
CREATE INDEX IF NOT EXISTS "idx_dashcomment_workspace_created" ON "DashboardComment"("workspaceId", "createdAt");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_presence_user" ON "PresenceHeartbeat"("userId");
CREATE INDEX IF NOT EXISTS "idx_presence_workspace_lastseen" ON "PresenceHeartbeat"("workspaceId", "lastSeen");
CREATE INDEX IF NOT EXISTS "idx_dashfilter_workspace_user" ON "DashboardFilter"("workspaceId", "userId");
CREATE INDEX IF NOT EXISTS "idx_dashfilter_workspace_shared" ON "DashboardFilter"("workspaceId", "shared");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_dashfilter_unique_name_workspace" ON "DashboardFilter"("workspaceId", "userId", "name") WHERE "deletedAt" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_worklog_workspace" ON "WorkLog"("workspaceId");
CREATE INDEX IF NOT EXISTS "idx_worklog_workspace_date" ON "WorkLog"("workspaceId", "date");
CREATE INDEX IF NOT EXISTS "idx_worklog_workspace_assignee" ON "WorkLog"("workspaceId", "assignee");
CREATE INDEX IF NOT EXISTS "idx_worklog_workspace_active_date" ON "WorkLog"("workspaceId", "date" DESC) WHERE "deletedAt" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "idx_company_name" ON "Company"("name");
CREATE INDEX IF NOT EXISTS "idx_company_status" ON "Company"("status");
CREATE INDEX IF NOT EXISTS "idx_company_plan" ON "Company"("plan");
CREATE INDEX IF NOT EXISTS "idx_auditlog_created" ON "AdminAuditLog"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_auditlog_actor" ON "AdminAuditLog"("actor");
CREATE INDEX IF NOT EXISTS "idx_announcement_active" ON "Announcement"("active");
CREATE INDEX IF NOT EXISTS "idx_announcement_target" ON "Announcement"("targetCompany");
CREATE INDEX IF NOT EXISTS "idx_supportticket_company" ON "SupportTicket"("company");
CREATE INDEX IF NOT EXISTS "idx_supportticket_status" ON "SupportTicket"("status");
CREATE INDEX IF NOT EXISTS "idx_supportticket_company_status" ON "SupportTicket"("company", "status");
CREATE INDEX IF NOT EXISTS "idx_collabpresence_module_item" ON "CollaborationPresence"("module", "itemId");
CREATE INDEX IF NOT EXISTS "idx_collabpresence_workspace_module" ON "CollaborationPresence"("workspaceId", "module");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_collabpresence_user_module_item" ON "CollaborationPresence"("userId", "module", "itemId");
CREATE INDEX IF NOT EXISTS "idx_adminnotif_read" ON "AdminNotification"("read");
CREATE INDEX IF NOT EXISTS "idx_adminnotif_created" ON "AdminNotification"("createdAt" DESC);
CREATE INDEX IF NOT EXISTS "idx_moduleview_workspace_module" ON "ModuleView"("workspaceId", "module");
CREATE INDEX IF NOT EXISTS "idx_moduleview_workspace_user_module" ON "ModuleView"("workspaceId", "userId", "module");
CREATE INDEX IF NOT EXISTS "idx_moduleview_workspace_shared" ON "ModuleView"("workspaceId", "shared");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_notifpref_user" ON "NotificationPreference"("userId");
CREATE INDEX IF NOT EXISTS "idx_notifpref_workspace" ON "NotificationPreference"("workspaceId");
`;
